name: 'Check SPDX Header and Licenses'
on:
  pull_request:
    branches: [ 'main' ]

jobs:
  check-licenses:
    name: License checks for SIL Kit sources
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Dependencies
        id: dep-install
        run: |
          sudo apt install licensecheck

      - name: Check Licenses
        id: license-check
        run: |
          sh ./SilKit/ci/check_licenses.sh
        shell: bash
