name: Update Docs

on:

  workflow_dispatch:
    inputs:
      repo_owner:
        required: true
      repo_name:
        required: true


jobs:

  trigger-ci:
    name: Trigger CI

    runs-on: ubuntu-latest

    steps:

      - name: Trigger Workflow
        env:
          GH_TOKEN: ${{ github.secrets.PAT_REPOSITORY_DISPATCH }}
        id: trigger-workflow
        run: |
           repo_owner=${{ inputs.repo_owner }}
           repo_name=${{ inputs.repo_name }}

           echo $repo_owner
           echo $repo_name

           gh workflow run remote_workflow.yaml \
           --repo ${{ github.secrets.REMOTE_REPO }} \
           --branch main \
           -f world=mars

