name: Update Docs

on:

  workflow_dispatch:

jobs:

  trigger-ci:
    name: Trigger CI

    runs-on: ubuntu-latest

    steps:

      - name: Trigger Workflow
        id: trigger-workflow
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |

           gh workflow run remote_workflow.yaml \
           --repo ${{ secrets.REMOTE_REPO }} \
           --ref main \
           -f world=mars

           sleep 5

           # Get the ID of the workflow by checking the latest run(ning) workflow
           run_id=$(gh \
             run list \
             -w remote_workflow.yaml \
             --limit 1 \
             --json workflowDatabaseId \
             -q '.[0].databaseId' \
             --repo ${{ secrets.REMOTE_REPO }})

           echo "run_id=${run_id}" >> $GITHUB_OUTPUT

      - name: Watch workflow
        id: watch-workflow
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          echo ${{ steps.trigger-workflow.outputs.run_id }}
          gh run watch \
          ${{ steps.trigger-workflow.outputs.run_id }} \
          --interval 3 \
          --compact \
          --exit-status \
          --repo ${{ secrets.REMOTE_REPO }}

          #ret=$(gh \
          #  run view \
          #  ${{ steps.trigger_workflow.outputs.run_id }} \
          #  --json conclusion \
          #  -q .conclusion \
          #  --repo ${{ secrets.REMOTE_REPO }})

          #echo "Remote workflow exit status: $ret"

          #if [ "$ret" != "sucess" ]; then
          #  exit 1
          #fi

